#include <iostream>
#include <cstdint>
#include <cmath>

/*
Platform: Project Euler
Problem: 12
Problem Name: Highly Divisible Triangular Number

Problem Statement:
The sequence of traingule number is generated by adding the natural numbers.
So the 7th triangular number would be 1+2+3+4+5+6+7 = 28. The first ten terms would be:
1,3,6,10,15,21,28,36,45,55,...

Let us list the factors of the first seven triangle numbers:
1: 3
3: 1,3
6: 1,2,3,6
...

We can see that 28 is the first triangle number to have over 5 divisors.
What is the value of the first triangle number with over five hundred divisors?
*/

uint64_t nth_triangular(uint64_t n)
{
    return n * (n + 1) / 2;
}

uint64_t num_divisors(uint64_t n)
{
    if (n == 1)
        return 1;
    uint64_t num_factors = 1;
    if (n % 2 == 0)
    {
        int cur = 1;
        while (n % 2 == 0)
        {
            n /= 2;
            cur++;
        }

        num_factors *= cur;
    }

    for (int i = 3; i <= sqrt(n); i += 2)
        if (n % i == 0)
        {
            int cur = 1;
            while (n % i == 0)
            {
                n /= i;
                cur++;
            };
            num_factors *= cur;
        }

    return num_factors * (1 + (n > 1));
}

int main()
{
    int n = 1;
    while (num_divisors(nth_triangular(n)) < 500)
    {
        std::cout << "n: " << n << ", nth_triangular: " << nth_triangular(n) << ", num_divisors of nth_triangular: " << num_divisors(nth_triangular(n)) << std::endl;
        n++;
    }

    std::cout << nth_triangular(n) << std::endl;
    // answer - 76576500
}