#include <cstdint>
#include <iostream>
#include <set>
#include <utility>
#include <vector>

/*
 * Consider all integer combinations of a^b for 2 <= a <= 5 and 2 <= b <= 5:
 *
 * ...
 *
 * If they are all placed in numerical order, with any repeats removed, we get
 * the following sequence of 15 distinct terms:
 *
 * ...
 *
 * How many distinct terms are in the sequence generated by a^b for 2 <= a <=
 * 100 and 2 <= b <= 100?
 * */
uint8_t log(uint8_t n, uint8_t base) {
  if (n == base)
    return 1;
  uint8_t x = 1;
  do {
    x += 1;
    n /= base;
  } while (n != base);

  return x;
}

int main() {
  std::vector<uint8_t> parents(101, 0);
  uint32_t result = 0;
  std::set<std::pair<uint8_t, uint16_t>> pairs;

  for (int i = 2; i <= 100; i++) {
    if (parents[i])
      continue;
    for (int j = i; j <= 100; j *= i)
      parents[j] = i;
  }

  for (uint8_t a = 2; a <= 100; a++) {
    for (uint8_t b = 2; b <= 100; b++) {
      if (!pairs.count({parents[a], log(a, parents[a]) * b})) {
        pairs.emplace(parents[a], log(a, parents[a]) * b);
        result += 1;
      }
    }
  }

  std::cout << result << std::endl;
  return 0;
  // answer - 9183
}
